// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCiheQSrduTZMTGRTLDHkblR62cc3ffasI',
    appId: '1:943376646148:web:ca0ddc183c623b5457b551',
    messagingSenderId: '943376646148',
    projectId: 'yadvi-seed-app-5f306',
    authDomain: 'yadvi-seed-app-5f306.firebaseapp.com',
    storageBucket: 'yadvi-seed-app-5f306.firebasestorage.app',
    measurementId: 'G-WXN21Y1S68',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXZICOBwTyZhwNhp03QkAk4A1JFz8aMFE',
    appId: '1:943376646148:android:8ab282dfec5f15f757b551',
    messagingSenderId: '943376646148',
    projectId: 'yadvi-seed-app-5f306',
    storageBucket: 'yadvi-seed-app-5f306.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCtPu7ll459O6IWOFrD1dSwXeXT0IdCAU',
    appId: '1:943376646148:ios:0675cbab3c019e1157b551',
    messagingSenderId: '943376646148',
    projectId: 'yadvi-seed-app-5f306',
    storageBucket: 'yadvi-seed-app-5f306.firebasestorage.app',
    iosBundleId: 'com.yadvi.fieldExecutiveApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBCtPu7ll459O6IWOFrD1dSwXeXT0IdCAU',
    appId: '1:943376646148:ios:0675cbab3c019e1157b551',
    messagingSenderId: '943376646148',
    projectId: 'yadvi-seed-app-5f306',
    storageBucket: 'yadvi-seed-app-5f306.firebasestorage.app',
    iosBundleId: 'com.yadvi.fieldExecutiveApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCiheQSrduTZMTGRTLDHkblR62cc3ffasI',
    appId: '1:943376646148:web:f5df39078a6847ce57b551',
    messagingSenderId: '943376646148',
    projectId: 'yadvi-seed-app-5f306',
    authDomain: 'yadvi-seed-app-5f306.firebaseapp.com',
    storageBucket: 'yadvi-seed-app-5f306.firebasestorage.app',
    measurementId: 'G-F8YR62T7CT',
  );
}
